/**
 * archetypes — content data owned by the party builder. `NpcDef` templates for generic (non-named) units:
 * crowd population, generic militia and Habsburg/enemy squads. Registered via `ContentRegistry.addArchetypes`,
 * which does NOT cross-reference `home` against POIs (unlike `addNpcs`) — `home: ''` is deliberate here.
 * `role` is 'generic' for civilians/neutral folk, 'enemy' for hostile squads used by EncounterDef `PlacedUnit`.
 */
import type { ContentRegistry } from '@core/content';
import type { NpcDef } from '@core/schemas';

export const archetypes: NpcDef[] = [
  {
    id: 'peasant', name: 'Peasant', faction: 'none', home: '', role: 'generic', archetype: 'peasant',
    attributes: { strength: 10, agility: 10, endurance: 10, wits: 9, presence: 9 },
    skills: { unarmed: 10, athletics: 10 },
    equipment: {},
    modelId: 'char.peasant',
    description: 'A village field-worker, unarmed and unremarkable — the Waldstätte\'s ordinary population.',
    historical: true, note: 'Subsistence farming on steep Alpine terrain was the economic base of all three Länder.',
  },
  {
    id: 'herder', name: 'Herder', faction: 'none', home: '', role: 'generic', archetype: 'herder',
    attributes: { strength: 11, agility: 12, endurance: 12, wits: 9, presence: 8 },
    skills: { athletics: 20, herbalism: 12, throwing: 15 },
    equipment: { mainHand: 'item.staff', ranged: 'item.sling', ammo: 'item.sling-stones', feet: 'item.wooden-shoes' },
    modelId: 'char.herder',
    description: 'An Alp herder, sling in hand against wolves, sure-footed from a life spent driving cattle up and down the Alpwirtschaft trails.',
    historical: true, note: 'Alpine transhumance (Alpwirtschaft) is the defining seasonal economy of the region.',
  },
  {
    id: 'fisher', name: 'Fisher', faction: 'none', home: '', role: 'generic', archetype: 'fisher',
    attributes: { strength: 10, agility: 11, endurance: 11, wits: 9, presence: 8 },
    skills: { athletics: 15, dagger: 12 },
    equipment: { mainHand: 'item.schweizerdolch' },
    inventory: [{ item: 'item.fishing-line', qty: 1 }],
    modelId: 'char.fisher',
    description: 'A lake fisherman of the shore villages, more at home on the water than the road.',
    historical: true, note: 'Lake-shore fishing communities (Gersau, Weggis, the Luzern basin) are attested for the period.',
  },
  {
    id: 'saeumer', name: 'Säumer', faction: 'saeumer', home: '', role: 'generic', archetype: 'saeumer',
    attributes: { strength: 13, agility: 11, endurance: 13, wits: 10, presence: 10 },
    skills: { spear: 20, athletics: 18, alpine: 20, trade: 15 },
    equipment: { mainHand: 'item.spiess', body: 'item.gambeson', feet: 'item.hobnailed-boots' },
    inventory: [{ item: 'item.mule-tack', qty: 1 }, { item: 'item.salt-sack', qty: 1 }],
    modelId: 'char.saeumer',
    description: 'A Gotthard muleteer, armed enough to see off casual robbers on the pass road.',
    historical: true, note: 'Säumergenossenschaft cooperatives working the Gotthard route are attested from the 14th century.',
  },
  {
    id: 'militia-spear', name: 'Spear Militia', faction: 'none', home: '', role: 'generic', archetype: 'militia',
    attributes: { strength: 12, agility: 11, endurance: 12, wits: 9, presence: 9 },
    skills: { spear: 25, shield: 15, 'armor-light': 15 },
    equipment: { mainHand: 'item.spiess', offHand: 'item.buckler', body: 'item.gambeson', head: 'item.eisenhut' },
    modelId: 'char.militia-spear',
    description: 'A Waldstätte freeman called up with his own spear, shield and Eisenhut, as the Landsgemeinde\'s levy required.',
    historical: true, note: 'The Confederate levy was drawn from armed freemen, not a standing professional force.',
  },
  {
    id: 'militia-halberd', name: 'Halberd Militia', faction: 'none', home: '', role: 'generic', archetype: 'militia',
    attributes: { strength: 13, agility: 10, endurance: 12, wits: 9, presence: 9 },
    skills: { halberd: 25, 'armor-light': 15 },
    equipment: { mainHand: 'item.halbarte', body: 'item.gambeson', head: 'item.eisenhut' },
    modelId: 'char.militia-halberd',
    description: 'A Confederate halberdier — the levy that broke the Habsburg column at Morgarten.',
    historical: true, note: 'Halberds are specifically named in chronicle accounts of the Confederate line at Morgarten.',
  },
  {
    id: 'militia-crossbow', name: 'Crossbow Militia', faction: 'none', home: '', role: 'generic', archetype: 'militia',
    attributes: { strength: 10, agility: 13, endurance: 10, wits: 11, presence: 9 },
    skills: { crossbow: 25, 'armor-light': 12 },
    equipment: { ranged: 'item.armbrust', ammo: 'item.bolzen', mainHand: 'item.schweizerdolch', body: 'item.gambeson' },
    modelId: 'char.militia-crossbow',
    description: 'A militia crossbowman, drilled to hold high ground and keep range.',
    historical: true, note: 'Stirrup-crossbows were common enough militia kit by 1300 for this to be an unremarkable levy role.',
  },
  {
    id: 'elder', name: 'Village Elder', faction: 'none', home: '', role: 'generic', archetype: 'elder',
    attributes: { strength: 8, agility: 7, endurance: 9, wits: 14, presence: 16 },
    skills: { leadership: 35, speech: 35, trade: 20 },
    equipment: { mainHand: 'item.staff' },
    modelId: 'char.elder',
    description: 'A grey-haired Landsgemeinde voice, past fighting age but not past being heard.',
    historical: true, note: 'The Landsgemeinde\'s consensus politics gave real standing to respected elders regardless of martial ability.',
  },
  {
    id: 'monk', name: 'Monk', faction: 'einsiedeln', home: '', role: 'generic', archetype: 'monk',
    attributes: { strength: 9, agility: 9, endurance: 10, wits: 14, presence: 13 },
    skills: { herbalism: 25, speech: 20, craft: 15 },
    equipment: { mainHand: 'item.staff' },
    modelId: 'char.monk',
    description: 'A Benedictine brother of the abbey, literate and skilled in the infirmary garden.',
    historical: true, note: 'Einsiedeln abbey (Benedictine, under Abbot Johannes von Schwanden from 1298) is the region\'s major monastic house; see LORE.md §2.',
  },
  {
    id: 'merchant', name: 'Merchant', faction: 'none', home: '', role: 'generic', archetype: 'merchant',
    attributes: { strength: 9, agility: 9, endurance: 9, wits: 13, presence: 12 },
    skills: { trade: 35, speech: 20 },
    equipment: { mainHand: 'item.messer' },
    modelId: 'char.merchant',
    description: 'A travelling trader working the lake ports and the Gotthard road, sharp about a Pfennig price.',
    historical: true, note: 'Cross-lake and Gotthard trade supported a real merchant class in Luzern, Zug and Zürich.',
  },
  {
    id: 'innkeeper', name: 'Innkeeper', faction: 'none', home: '', role: 'generic', archetype: 'innkeeper',
    attributes: { strength: 11, agility: 9, endurance: 11, wits: 11, presence: 13 },
    skills: { trade: 25, speech: 20 },
    equipment: { mainHand: 'item.staff' },
    modelId: 'char.innkeeper',
    description: 'Keeper of a village tavern, the best source of local gossip in any settlement.',
    historical: true, note: 'Taverns are the ordinary period social hub reflected in the exploration builder\'s NPC schedules.',
  },
  {
    id: 'habsburg-footman', name: 'Habsburg Footman', faction: 'habsburg', home: '', role: 'enemy', archetype: 'footman',
    attributes: { strength: 13, agility: 11, endurance: 12, wits: 9, presence: 9 },
    skills: { spear: 25, shield: 20, 'armor-heavy': 15 },
    equipment: { mainHand: 'item.spiess', offHand: 'item.heater-shield', body: 'item.mail-shirt', head: 'item.eisenhut' },
    modelId: 'char.habsburg-footman',
    description: 'A levied Aargau footman garrisoning a Habsburg holding, better-equipped than the Confederate militia he faces.',
    historical: true, note: 'Habsburg garrisons drew on the Aargau heartland; mail was common issue there unlike in the Waldstätte.',
  },
  {
    id: 'habsburg-crossbowman', name: 'Habsburg Crossbowman', faction: 'habsburg', home: '', role: 'enemy', archetype: 'crossbowman',
    attributes: { strength: 10, agility: 13, endurance: 10, wits: 10, presence: 9 },
    skills: { crossbow: 30, 'armor-light': 12 },
    equipment: { ranged: 'item.armbrust', ammo: 'item.bolzen', mainHand: 'item.schweizerdolch', body: 'item.gambeson', head: 'item.leather-cap' },
    modelId: 'char.habsburg-crossbowman',
    description: 'A professional crossbowman in Habsburg pay, drilled to hold range and reload under fire.',
    historical: true, note: 'Paid crossbow companies were standard garrison and campaign troops for a house of Habsburg\'s standing.',
  },
  {
    id: 'habsburg-sergeant', name: 'Habsburg Sergeant', faction: 'habsburg', home: '', role: 'enemy', archetype: 'sergeant',
    attributes: { strength: 13, agility: 12, endurance: 13, wits: 11, presence: 12 },
    skills: { sword: 35, shield: 25, leadership: 20, 'armor-heavy': 20 },
    equipment: { mainHand: 'item.schwert', offHand: 'item.heater-shield', body: 'item.mail-shirt', head: 'item.bascinet' },
    modelId: 'char.habsburg-sergeant',
    description: 'A mounted-man\'s sergeant commanding a Habsburg squad, sword-trained and hard to rattle.',
    historical: true, note: 'Ministerial sergeants (Dienstmannen) filled the officer roles below knightly rank in Habsburg service.',
  },
  {
    id: 'habsburg-knight', name: 'Habsburg Knight', faction: 'habsburg', home: '', role: 'enemy', archetype: 'knight',
    attributes: { strength: 15, agility: 12, endurance: 14, wits: 11, presence: 13 },
    skills: { spear: 40, sword: 35, shield: 30, 'armor-heavy': 35 },
    equipment: { mainHand: 'item.lance', offHand: 'item.heater-shield', body: 'item.coat-of-plates', head: 'item.bascinet' },
    modelId: 'char.habsburg-knight',
    description: 'A mounted Aargau knight in coat-of-plates over mail, couched lance levelled — the Habsburg column\'s cavalry at Morgarten.',
    historical: true, note: 'Duke Leopold I\'s column at Morgarten was heavy on Aargau knightly cavalry; see LORE.md §1.',
  },
  {
    id: 'habsburg-squire', name: 'Habsburg Squire', faction: 'habsburg', home: '', role: 'enemy', archetype: 'squire',
    attributes: { strength: 12, agility: 12, endurance: 12, wits: 10, presence: 10 },
    skills: { sword: 20, shield: 15, 'armor-heavy': 12 },
    equipment: { mainHand: 'item.schwert', offHand: 'item.buckler', body: 'item.gambeson', head: 'item.leather-cap' },
    modelId: 'char.habsburg-squire',
    description: 'A knight\'s squire, not yet dubbed, fighting on foot until he earns his spurs.',
    historical: true, note: 'Squires accompanied knights on campaign and fought dismounted before knighthood, standard period practice.',
  },
  {
    id: 'bailiff-guard', name: 'Bailiff\'s Guard', faction: 'habsburg', home: '', role: 'enemy', archetype: 'guard',
    attributes: { strength: 12, agility: 11, endurance: 11, wits: 10, presence: 10 },
    skills: { sword: 20, 'armor-light': 15 },
    equipment: { mainHand: 'item.messer', body: 'item.gambeson', head: 'item.leather-cap' },
    modelId: 'char.bailiff-guard',
    description: 'One of Landvogt Gessler\'s or Landenberg\'s men, enforcing tolls and the hat on the pole at Altdorf.',
    historical: 'legend', note: 'Bailiffs\' armed retinues are part of the Tell/Gessler tradition (Weisses Buch von Sarnen); see LORE.md §5–6.',
  },
  {
    id: 'abbey-man-at-arms', name: 'Abbey Man-at-Arms', faction: 'einsiedeln', home: '', role: 'enemy', archetype: 'man-at-arms',
    attributes: { strength: 12, agility: 11, endurance: 12, wits: 10, presence: 10 },
    skills: { spear: 20, shield: 15, 'armor-light': 15 },
    equipment: { mainHand: 'item.spiess', offHand: 'item.buckler', body: 'item.gambeson' },
    modelId: 'char.abbey-man-at-arms',
    description: 'One of the abbey\'s own retainers, defending Einsiedeln\'s gate the night of the Marchenstreit raid.',
    historical: true, note: 'Einsiedeln, like other landed abbeys, maintained an armed retinue for its own protection and advocacy disputes.',
  },
  {
    id: 'toll-collector', name: 'Toll Collector', faction: 'habsburg', home: '', role: 'generic', archetype: 'toll-collector',
    attributes: { strength: 9, agility: 9, endurance: 9, wits: 11, presence: 11 },
    skills: { trade: 25, speech: 15 },
    equipment: { mainHand: 'item.messer' },
    modelId: 'char.toll-collector',
    description: 'A bailiff\'s clerk running a road or bridge toll — resented, and not always honest about the rate.',
    historical: true, note: 'Habsburg toll stations on the roads and the Reuss bridges were a real and resented source of friction.',
  },
  {
    id: 'raubritter', name: 'Raubritter', faction: 'raubritter', home: '', role: 'enemy', archetype: 'raubritter',
    attributes: { strength: 13, agility: 12, endurance: 12, wits: 9, presence: 9 },
    skills: { sword: 25, shield: 15, 'armor-heavy': 15 },
    equipment: { mainHand: 'item.schwert', offHand: 'item.buckler', body: 'item.mail-shirt', head: 'item.leather-cap' },
    modelId: 'char.raubritter',
    description: 'A landless knight or deserter turned road-bandit in the Aargau borderland — a named man, not a fantasy bandit.',
    historical: 'invented', note: 'Bands of landless knights and deserters are a plausible, attested social phenomenon of the period; see LORE.md §2.',
  },
  {
    id: 'boatman', name: 'Boatman', faction: 'none', home: '', role: 'generic', archetype: 'boatman',
    attributes: { strength: 12, agility: 11, endurance: 12, wits: 9, presence: 9 },
    skills: { athletics: 20, trade: 10 },
    equipment: { mainHand: 'item.staff' },
    modelId: 'char.boatman',
    description: 'A lake ferryman working the crossing between the shore ports — Brunnen, Flüelen, Treib.',
    historical: true, note: 'Boat traffic was the fastest way to move along the lake shore, as the Prologue\'s Rütli crossing uses.',
  },
  {
    id: 'child', name: 'Child', faction: 'none', home: '', role: 'generic', archetype: 'child',
    attributes: { strength: 6, agility: 10, endurance: 8, wits: 9, presence: 9 },
    skills: {},
    equipment: {},
    modelId: 'char.child',
    description: 'A village child, present for colour and dialogue only — never a combatant.',
    historical: true, note: 'Populating settlements with families rather than only fighting-age adults keeps the crowd historically plausible.',
  },
  {
    id: 'woman-peasant', name: 'Peasant Woman', faction: 'none', home: '', role: 'generic', archetype: 'peasant',
    attributes: { strength: 9, agility: 10, endurance: 10, wits: 10, presence: 10 },
    skills: { herbalism: 12, craft: 12 },
    equipment: { mainHand: 'item.staff' },
    modelId: 'char.woman-peasant',
    description: 'A farm or household worker of the village — spinning, dairying, brewing, and running the household economy.',
    historical: true, note: 'Rural households of the period depended on women\'s labour in dairying, textiles and farm management.',
  },
];

export function register(c: ContentRegistry): void {
  c.addArchetypes(archetypes);
}
